# Generated by Django 4.1.1 on 2022-11-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=255, unique=True, verbose_name='Телефон')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото сотрудника')),
                ('speciality', models.CharField(default='Терапевт', max_length=255, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
