# Generated by Django 4.1.1 on 2022-11-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('administrator', 'Администратор'), ('doctor', 'Доктор')], default='administrator', max_length=255, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='speciality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Специальность'),
        ),
    ]
