# Generated by Django 4.1.1 on 2022-11-19 06:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('phone', models.CharField(max_length=255, unique=True, verbose_name='Телефон')),
                ('time_zone', timezone_field.fields.TimeZoneField(default='Europe/Moscow')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(auto_now=True, db_index=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('male', 'Mужчина'), ('female', 'Женщина')], default='male', max_length=255, verbose_name='Пол')),
                ('phone', models.CharField(default='8-999-888-77-66', max_length=255, unique=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время начала приема')),
                ('dateFinish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время окончания приема')),
                ('service', models.CharField(default='Медицинский осмотр', max_length=255, verbose_name='Услуга')),
                ('status', models.CharField(choices=[('not_confirmed', 'Не подтвержден'), ('confirmed', 'Подтвержден'), ('reception_completed', 'Прием завершен'), ('Canceled', 'Отменён'), ('no_show', 'Неявка')], default='not_confirmed', max_length=255)),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_events', to='scheduler.cabinet', verbose_name='Кабинет')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_events', to='scheduler.customer', verbose_name='Клиент')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_events', to='employee.profile', verbose_name='Лечащий врач')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.AddField(
            model_name='cabinet',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='scheduler.clinic', verbose_name='Клиника'),
        ),
        migrations.AlterUniqueTogether(
            name='cabinet',
            unique_together={('name', 'clinic')},
        ),
    ]
