# Generated by Django 4.1.1 on 2022-09-08 06:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('phone', models.CharField(max_length=255, unique=True, verbose_name='Телефон')),
                ('time_zone', timezone_field.fields.TimeZoneField(default='Asia/Barnaul')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
            },
        ),
        migrations.CreateModel(
            name='StomatologyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(db_index=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=255, unique=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Пользователь стоматологии',
                'verbose_name_plural': 'Пользователи стоматологии',
                'ordering': ['-date_of_birth'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('stomatologyuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.stomatologyuser')),
                ('gender', models.CharField(choices=[('male', 'Mужчина'), ('female', 'Женщина')], default='male', max_length=255, verbose_name='Пол')),
                ('duration_of_admission', models.TimeField(default=datetime.time(0, 15), verbose_name='Длительность приема')),
                ('service', models.CharField(max_length=255, verbose_name='Услуга')),
                ('status', models.CharField(choices=[('not_confirmed', 'Не подтвержден'), ('confirmed', 'Подтверждение'), ('reception_completed', 'Прием завершен'), ('Canceled', 'Отменён'), ('no_show', 'Неявка')], default='not_confirmed', max_length=255)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
            bases=('scheduler.stomatologyuser',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('stomatologyuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.stomatologyuser')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото сотрудника')),
                ('speciality', models.CharField(max_length=255, verbose_name='Специальность')),
                ('clinic', models.ManyToManyField(related_name='employees', to='scheduler.clinic', verbose_name='Клиника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудник',
                'ordering': ['speciality'],
            },
            bases=('scheduler.stomatologyuser',),
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Кабинет')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='scheduler.clinic', verbose_name='Клиника')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата приема')),
                ('time', models.TimeField(default=datetime.time(8, 0), verbose_name='Длительность приема')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_events', to='scheduler.cabinet', verbose_name='Кабинет')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_events', to='scheduler.customer', verbose_name='Клиент')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_events', to='scheduler.employee', verbose_name='Лечащий врач')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
