# Generated by Django 4.1.1 on 2022-09-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='duration_of_admission',
        ),
    ]
