# Generated by Django 4.1.1 on 2022-11-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('not_confirmed', 'Не подтвержден'), ('confirmed', 'Подтвержден'), ('reception_completed', 'Прием завершен'), ('canceled', 'Отменён'), ('no_show', 'Неявка')], default='not_confirmed', max_length=255),
        ),
    ]
