# Generated by Django 4.1.1 on 2022-09-08 07:25

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['speciality'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Moscow'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('not_confirmed', 'Не подтвержден'), ('confirmed', 'Подтвержден'), ('reception_completed', 'Прием завершен'), ('Canceled', 'Отменён'), ('no_show', 'Неявка')], default='not_confirmed', max_length=255),
        ),
    ]
