# Generated by Django 4.1.1 on 2022-11-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateFinish',
            field=models.DateTimeField(verbose_name='Дата и время окончания приема'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dateStart',
            field=models.DateTimeField(verbose_name='Дата и время начала приема'),
        ),
    ]
