# Generated by Django 4.1.1 on 2022-09-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_rename_name_customer_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
