# Generated by Django 4.1.1 on 2022-11-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_profile_image_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата рождения'),
        ),
    ]
