# Generated by Django 4.1.1 on 2022-09-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_clinic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
