# Generated by Django 4.1.1 on 2022-11-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_rename_datefinish_event_date_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='end_of_the_day',
            field=models.CharField(default='17:00', max_length=10, verbose_name='Конец рабочего дня'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='start_of_the_day',
            field=models.CharField(default='08:00', max_length=10, verbose_name='Начало рабочего дня'),
        ),
    ]
