# Generated by Django 4.1.1 on 2022-11-30 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_profile_role'),
        ('scheduler', '0005_clinic_end_of_the_day_clinic_start_of_the_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_events', to='employee.profile', verbose_name='Лечащий врач'),
        ),
    ]
