# Generated by Django 4.1.1 on 2022-12-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_alter_event_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ['is_main'], 'verbose_name': 'Клиника', 'verbose_name_plural': 'Клиники'},
        ),
        migrations.AddField(
            model_name='clinic',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Является главной'),
        ),
    ]
