# Generated by Django 4.1.1 on 2022-12-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_alter_clinic_options_clinic_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ['-is_main'], 'verbose_name': 'Клиника', 'verbose_name_plural': 'Клиники'},
        ),
    ]
