# Generated by Django 4.1.1 on 2022-12-14 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_profile_role'),
        ('scheduler', '0008_alter_clinic_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Дата и время начала дежурства')),
                ('date_finish', models.DateTimeField(verbose_name='Дата и время окончания дежурства')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_shift_cabinet', to='scheduler.cabinet', verbose_name='Кабинет')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duty_shift', to='employee.profile', verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'Дежурство',
                'verbose_name_plural': 'Дежурства',
            },
        ),
    ]
