# Generated by Django 4.1.1 on 2022-12-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_profile_role'),
        ('scheduler', '0009_dutyshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyshift',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_shift', to='employee.profile', verbose_name='Доктор'),
        ),
    ]
