# Generated by Django 4.1.1 on 2022-12-22 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
        ('scheduler', '0010_alter_dutyshift_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_services', to='price.pricelist', verbose_name='Прайс-лист'),
        ),
    ]
