# Generated by Django 4.1.1 on 2022-12-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_clinic_price_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Услуга'),
        ),
    ]
